name: 'pipeline_monitoring'
version: '1.0.0'
config-version: 2

profile: 'pipeline_monitoring'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']

models:
  pipeline_monitoring:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  pipeline_monitoring:
    +schema: raw
